{% set name = "px4tools" %}
{% set version = "0.8.0" %}
{% set sha256 = "739e9e02b5b3945b472465653f20a65a66e51a7bf97ded912e7f443cf7aff460" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/dronecrew/px4tools/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  entry_points:
    - px42csv=px4tools.px42csv:main
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - scipy
    - numpy
    - pandas
    - matplotlib
    - basemap

test:
  import:
    - px4tools
  commands:
    - px42csv -h

about:
  home: https://github.com/dronecrew/px4tools
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'Python log crunching for PX4.'

extra:
  recipe-maintainers:
    - jgoppert

#  vim: set et fenc=utf-8 ff=unix sts=0 sw=2 ts=2 : 
