{% set version = "0.7.7" %}

package:
  name: px4tools
  version: {{ version }}

source:
  url: https://github.com/dronecrew/px4tools/archive/v{{ version }}.tar.gz
  sha256: 5f04382ce192e99a6b70f85183a1c1c19f026034f81c7612d36e1ea41ab6ea7f

build:
  number: 1000
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"
  entry_points:
    - px42csv = px4tools.px42csv:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - scipy
    - numpy
    - pandas
    - matplotlib
    - basemap

test:
  imports:
    - px4tools
  commands:
    - px42csv -h

about:
  home: https://github.com/dronecrew/px4tools
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'Python log crunching for PX4'

extra:
  recipe-maintainers:
    - jgoppert
