{% set version = "0.9.6" %}

package:
  name: px4tools
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/px4tools/px4tools-{{ version }}.tar.gz
  sha256: 602aeddbc74244aec648a19c90bc9d81ecbfc2bd997302eb072a62e6d4a91e68

build:
  number: 1001
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"
  entry_points:
    - px42csv = px4tools.px42csv:main

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - control >=0.7.0
    - matplotlib-base >=2.2.2
    - numpy >=1.13.3
    - pandas >=0.23.1
    - python-dateutil >=2.5.0
    - pyulog >=0.6.0
    - scipy >=1.1.0
    - basemap  # looks like this one is optional now.
    # FIXME: Missing from conda-forge but apperentely one can import px4tools without it.
    # - transforms3d >=0.3.1

test:
  imports:
    - px4tools
  commands:
    - px42csv -h

about:
  home: https://github.com/dronecrew/px4tools
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'Python log crunching for PX4'

extra:
  recipe-maintainers:
    - jgoppert
