travis:
  secure:
    BINSTAR_TOKEN: lB0iV3lsknuw9DFuSakrPPlUc0keimYJLH8KBL23UF905NzqwmgSrLHPCRkojFfKMPxyZtwSEYPkb5uqVACidKkZoxNH2HWLuMtB/++xKcj+IeynNMSPBDr08uYAJrOw6lXP0K6p2l3Q7EQg4Hv5TEdSUg0Tz8LT1MRvs4WgQYBY9JDmf1IK0CEmxPR9kyi3fHBntbu9i4Q2xfZ1+KTVvRKcvvR5k2y9O0fWDAKtRbye6+47QktbUZWspYYbLsRLj1tP5NdQNxdVSkPFvoRinER3K+3VThbD9yQMqcTUy2/c7KmULXDabSdqdoEkowQnV1rb8ze4aTerFngAUhON48iHco9lI2sdaUzsDkR3SJfi2XrtlVIr//0ojMBZ3fWj2Nxd6C2Rrxeno+flY4xF/+DRQ22QPZr6hRHGovZhGvoENybmRZ7MMGkOYwQ5bbPYEOCxm/zGcYsTkBZITnt4f5wM8HurIIfP+DcB9vhcdIDN4bWaG0FOznEFfpx2krDbEf/RuCwbFq2OyoGmxom9pWOofEHWeSgYZt5k/mrQpHwD28HfXxfCZ1cv6Ohv9AEZ7jUhNN6HJgljzFVGjmNMcCw0J5a4Q1q5+oDby6D2U7XJSPevF0+p0ryl7yMMRXQrswhNm+uXTSRpyZrlRpJin1xjbrsxzio8Qux/hZ1ODTk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
