appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: VIn4LS0eys4MUHG5NLKU7fFu4KgVuA8UJqjgv739dEJYR4ZUwvVIrq/DluauUc98gnMO3eDFrWI9LS4VygPcdOQazlr1QxgR7sCdjtqdXz2A3vVHzYZzMUdPv/p0hQCaGLIV7ssc144B+CzOFXj8whvwNI5k2/EjllIUo22VtboIIFOpbQCazz7ZgxwfY/J70WO8GKU5gBhISafes5LBPHEpKQJfPAp/uWq4A6uC6EvSbaJ87+rXmeYL98eRCQb88DKWeO/I/w53okc072uCps9fApgQ8clCwreUlC80/dnVS1ZVUKjzybCwI8S+v96CN7QItNfHVKdYVKrMQDuHKm6YLw5S3LVnLKfdReXVHxs7qpeZNUqQsoBbjNgjZTMAVWHhtMA7HqioDnDzYHmgZnWffLH10KhRn5kuo2iKZIH6j/WaFswl74Lm3OR1DqN8VZ5BrXYS0iIoc2xb+B2AKuq/mAQDhMhpUSFWHY4lZar4VOPVihv1JNJfcOqH2ya2TyMTtrGOCmCQ70w52H03irmKYOu26KnEtYkJVp/e5+vanCZAFK5lDNHZZN0EyKnlpmnd5eP0zePCZkyWetL3zLaRBTFTTewXFs6TVg/j1yb3cByRIGcvKwIc131IPengdWfDXcLqdaVAVzqnkHBxKKdFcbvMcxLk9/Zuda3Lr2o=}
conda_forge_output_validation: true
